<?php
/**
 * Initialize the custom theme options.
 */
add_action( 'init', 'custom_theme_options' );

/**
 * Build the custom settings & update OptionTree.
 */
function custom_theme_options() {
  
  /* OptionTree is not loaded yet, or this is not an admin request */
  if ( ! function_exists( 'ot_settings_id' ) || ! is_admin() )
    return false;
    
  /**
   * Get a copy of the saved settings array. 
   */
  $saved_settings = get_option( ot_settings_id(), array() );
  
  /**
   * Custom settings array that will eventually be 
   * passes to the OptionTree Settings API Class.
   */
  $custom_settings = array( 
    'contextual_help' => array( 
      'content'       => array( 
        array(
          'id'        => 'help',
          'title'     => 'Help',
          'content'   => '<p><a href="https://www.jdtrendz.com/">Contact Support</a>.</p>'
        )
      ),
      'sidebar'       => ''
    ),
    'sections'        => array( 
      
      array(
        'id'          => 'featured_music',
        'title'       => 'FEATURED MUSIC'
      ),
      array(
        'id'          => 'color_bg',
        'title'       => 'BACKGROUND COLOR'
),
      array(
        'id'          => 'top_artiste',
        'title'       => 'TOP ARTISTE'
),      
      
array(
        'id'          => 'sticky_adsfooter',
        'title'       => 'STICKY ADS FOOTER'

),      
      
array(
        'id'          => 'post_watermark',
        'title'       => 'POST WATERMARK'

),      
      
array(
        'id'          => 'browser_bar_bg',
        'title'       => 'BROWSER BAR COLOR'
      )
    ),
    'settings'        => array( 
      array(
        'id'          => 'logo_image',
        'label'       => 'Logo Image',
        'desc'        => 'Upload your logo using the Upload Button or insert image URL.',
        'std'         => 'https://i.ibb.co/KxT8JNV/images.png',
        'type'        => 'upload',
        'section'     => 'general_settings',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'favicon',
        'label'       => 'Favicon',
        'desc'        => 'Upload a 32 x 32 px image that will represent your website\'s favicon.',
        'std'         => 'https://i.ibb.co/KxT8JNV/images.png',
        'type'        => 'upload',
        'section'     => 'general_settings',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'touch_icon',
        'label'       => 'Touch icon',
        'desc'        => 'Upload a 152 x 152 px image that will represent your website\'s touch icon for iOS 2.0+ and Android 2.1+ devices.',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'general_settings',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'copy_right_year',
        'label'       => 'Copyright Year',
        'desc'        => 'Enter the Year you started your blog ex 2018',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'general_settings',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'header_code',
        'label'       => 'Header Code',
        'desc'        => 'Enter the code which you need to place before closing  tag. (ex: Google Webmaster Tools verification, Bing Webmaster Center, BuySellAds Script, Alexa verification etc.)',
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'general_settings',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'footer_code',
        'label'       => 'Footer Code',
        'desc'        => 'Enter the codes which you need to place in your footer. (ex: Google Analytics, Clicky, STATCOUNTER, Woopra, Histats, etc.).',
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'general_settings',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'custom_css',
        'label'       => 'Custom CSS',
        'desc'        => 'You can enter custom CSS code here to further customize your theme. This will override the default CSS used on your site.',
        'std'         => '',
        'type'        => 'css',
        'section'     => 'styling_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'chrome_header_bar_address_color',
        'label'       => 'Chrome Header Bar/Address Color',
        'desc'        => 'Change the Color of Header Bar/Address Bar in Chrome',
        'std'         => '#060',
        'type'        => 'colorpicker',
        'section'     => 'styling_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'theme_color',
        'label'       => 'Theme Color',
        'desc'        => 'choice a theme color',
        'std'         => '#060',
        'type'        => 'colorpicker',
        'section'     => 'styling_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_1_image',
        'label'       => 'FEATURED MUSIC (1) IMAGE',
        'desc'        => 'ENTER FEATURED MUSIC (1) IMAGE',
        'std'         => 'https://i.ibb.co/YfjpFtW/images.jpg',
        'type'        => 'upload',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_1_title',
        'label'       => 'FEATURED MUSIC (1) TITLE',
        'desc'        => 'FEATURED MUSIC (1) TITLE',
        'std'         => 'Ifunaya',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_1_artist',
        'label'       => 'FEATURED MUSIC (1) ARTIST',
        'desc'        => 'FEATURED MUSIC (1) ARTIST',
        'std'         => 'Psuare',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_1_url',
        'label'       => 'FEATURED MUSIC (1) URL',
        'desc'        => 'ENTER THE URL OF THE FEATURED MUSIC e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_2_image',
        'label'       => 'FEATURED MUSIC (2) IMAGE',
        'desc'        => 'ENTER FEATURED MUSIC (2) IMAGE',
        'std'         => 'https://i.ibb.co/2N2LLKT/Tiwa-Savage-ft-Wizkid-Spellz-Ma-Lo-Video-1024x423.png',
        'type'        => 'upload',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_2_title',
        'label'       => 'FEATURED MUSIC (2) TITLE',
        'desc'        => 'FEATURED MUSIC (2) TITLE',
        'std'         => 'Soco',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_2_artist',
        'label'       => 'FEATURED MUSIC (2) ARTIST',
        'desc'        => 'FEATURED MUSIC (2) ARTIST',
        'std'         => 'Wizkid',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_2_url',
        'label'       => 'FEATURED MUSIC (2) URL',
        'desc'        => 'ENTER THE URL OF THE FEATURED VIDEO e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_3_image',
        'label'       => 'FEATURED MUSIC (3) IMAGE',
        'desc'        => 'ENTER FEATURED MUSIC (3) IMAGE',
        'std'         => 'https://i.ibb.co/P6s33hL/images-2.jpg',
        'type'        => 'upload',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_3_title',
        'label'       => 'FEATURED MUSIC (3) TITLE',
        'desc'        => 'FEATURED MUSIC (3) TITLE',
        'std'         => 'Assurance',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_3_artist',
        'label'       => 'FEATURED MUSIC (3) ARTIST',
        'desc'        => 'FEATURED MUSIC (3) ARTIST',
        'std'         => 'Davido',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_3_url',
        'label'       => 'FEATURED MUSIC (3) URL',
        'desc'        => 'ENTER THE URL OF THE FEATURED MUSIC e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_4_image',
        'label'       => 'FEATURED MUSIC (4) IMAGE',
        'desc'        => 'ENTER FEATURED MUSIC (4) IMAGE',
        'std'         => 'https://i.ibb.co/yWx4nXg/images-6.jpg',
        'type'        => 'upload',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_4_title',
        'label'       => 'FEATURED MUSIC (4) TITLE',
        'desc'        => 'FEATURED MUSIC (4) TITLE',
        'std'         => 'Jealous',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_4_artist',
        'label'       => 'FEATURED MUSIC (4) ARTIST',
        'desc'        => 'FEATURED MUSIC (4) ARTIST',
        'std'         => 'Fireboy',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
		array(
        'id'          => 'featured_music_4_url',
        'label'       => 'FEATURED MUSIC 4 URL',
        'desc'        => 'ENTER THE URL OF THE FEATURED MUSIC e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'featured_music',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),

      array(
        'id'          => 
'featured_music_5_image',
        'label'       => 'FEATURED MUSIC (5) IMAGE',
        'desc'        => 'ENTER FEATURED MUSIC (5) IMAGE',
        'std'         => 'https://i.ibb.co/yWx4nXg/images-6.jpg',
        'type'        => 'upload',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_5_title',
        'label'       => 'FEATURED MUSIC (5) TITLE',
        'desc'        => 'FEATURED MUSIC (5) TITLE',
        'std'         => 'Jealous',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_5_artist',
        'label'       => 'FEATURED MUSIC (5) ARTIST',
        'desc'        => 'FEATURED MUSIC (5) ARTIST',
        'std'         => 'Fireboy',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
		array(
        'id'          => 'featured_music_5_url',
        'label'       => 'FEATURED MUSIC 5 URL',
        'desc'        => 'ENTER THE URL OF THE FEATURED MUSIC e.g https://www.jdtrendz.com/fireboy',
        'std'         => 'https://www.jdtrendz.com',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),

      array(
        'id'          =>

'featured_music_6_image',
        'label'       => 'FEATURED MUSIC (6) IMAGE',
        'desc'        => 'ENTER FEATURED MUSIC (6) IMAGE',
        'std'         => 'https://i.ibb.co/yWx4nXg/images-6.jpg',
        'type'        => 'upload',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_6_title',
        'label'       => 'FEATURED MUSIC (6) TITLE',
        'desc'        => 'FEATURED MUSIC (6) TITLE',
        'std'         => 'Jealous',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_6_artist',
        'label'       => 'FEATURED MUSIC (6) ARTIST',
        'desc'        => 'FEATURED MUSIC (6) ARTIST',
        'std'         => 'Fireboy',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
		array(
        'id'          => 'featured_music_6_url',
        'label'       => 'FEATURED MUSIC 6 URL',
        'desc'        => 'ENTER THE URL OF THE FEATURED MUSIC e.g https://www.jdtrendz.com/fireboy',
        'std'         => 'https://www.jdtrendz.com',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),

      array(
        'id'          =>
'featured_music_7_image',
        'label'       => 'FEATURED MUSIC (7) IMAGE',
        'desc'        => 'ENTER FEATURED MUSIC (7) IMAGE',
        'std'         => 'https://i.ibb.co/yWx4nXg/images-6.jpg',
        'type'        => 'upload',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_7_title',
        'label'       => 'FEATURED MUSIC (7) TITLE',
        'desc'        => 'FEATURED MUSIC (7) TITLE',
        'std'         => 'Jealous',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_7_artist',
        'label'       => 'FEATURED MUSIC (7) ARTIST',
        'desc'        => 'FEATURED MUSIC (7) ARTIST',
        'std'         => 'Fireboy',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
		array(
        'id'          => 'featured_music_7_url',
        'label'       => 'FEATURED MUSIC 7 URL',
        'desc'        => 'ENTER THE URL OF THE FEATURED MUSIC e.g https://www.jdtrendz.com/fireboy',
        'std'         => 'https://www.jdtrendz.com',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),

      array(
        'id'          =>
'featured_music_8_image',
        'label'       => 'FEATURED MUSIC (8) IMAGE',
        'desc'        => 'ENTER FEATURED MUSIC (8) IMAGE',
        'std'         => 'https://i.ibb.co/yWx4nXg/images-6.jpg',
        'type'        => 'upload',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_8_title',
        'label'       => 'FEATURED MUSIC (8) TITLE',
        'desc'        => 'FEATURED MUSIC (8) TITLE',
        'std'         => 'Jealous',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_music_8_artist',
        'label'       => 'FEATURED MUSIC (8) ARTIST',
        'desc'        => 'FEATURED MUSIC (8) ARTIST',
        'std'         => 'Fireboy',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
		array(
        'id'          => 'featured_music_8_url',
        'label'       => 'FEATURED MUSIC 8 URL',
        'desc'        => 'ENTER THE URL OF THE FEATURED MUSIC e.g https://www.jdtrendz.com/fireboy',
        'std'         => 'https://www.jdtrendz.com',
        'type'        => 'text',
        'section'     => 'featured_musics',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),

      array(
        'id'          =>
'color_bg_light',
        'label'       => '<big>Background Color Light Version</big>',
        'desc'        => 'You can use color code like <b>#56a713</b> or color name like <b>green</b>. Save to use default',
        'std'         => '#56a713',
        'type'        => 'text',
        'section'     => 'color_bg',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          =>
'color_bg_dark',
        'label'       => '<big>Background Color Dark Version</big>',
        'desc'        => 'You can use color code like <b>#314c0c</b> or color name like <b>green</b>. Save to use default',
        'std'         => '#314c0c',
        'type'        => 'text',
        'section'     => 'color_bg',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 
'color_bg_media_of_week',
        'label'       => '<big>Background Color for Music and Video of the Week</big>',
        'desc'        => 'You can use color code like <b>#f0f9f0</b> or color name like <b>honeydew</b>. <u>Recommendation: Use lighter color for this.</u> Save to use default.',
        'std'         => '#f0f9f0',
        'type'        => 'text',
        'section'     => 'color_bg',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 
'text_color',
        'label'       => '<big>Background Color for Clickable Texts</big>',
        'desc'        => 'You can use color code like <b>#73990b</b> or color name like <b>green</b>. Save to use default',
        'std'         => '#73990b',
        'type'        => 'text',
        'section'     => 'color_bg',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          =>
'random_button_bg_color',
        'label'       => '<big>Background Color for Random Buttons</big>',
        'desc'        => 'You can use color code like <b>#ff0000</b> or color name like <b>red</b>. Save to use default',
        'std'         => '#ff0000',
        'type'        => 'text',
        'section'     => 'color_bg',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
'id'          =>
'sticky_adsfooter_bg_color',
        'label'       => '<big>Background Color for Sticky Ads Footer</big>',
        'desc'        => 'You can use color code like <b>#baef7b</b> or color name like <b>red</b>. Save to use default',
        'std'         => '#baef7b',
        'type'        => 'text',
        'section'     => 'color_bg',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
'id'          =>
'trendingpost_title_color',
        'label'       => '<big>Title Color for Trending Posts</big>',
        'desc'        => 'You can use color code like <b>#000000</b> or color name like <b>black</b>. Save to use default',
        'std'         => '#000000',
        'type'        => 'text',
        'section'     => 'color_bg',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
'id'          =>
'latestpost_title_color',
        'label'       => '<big>Title Color for Latest Posts</big>',
        'desc'        => 'You can use color code like <b>#000000</b> or color name like <b>black</b>. Save to use default',
        'std'         => '#000000',
        'type'        => 'text',
        'section'     => 'color_bg',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 
 'top_artiste_1',
        'label'       => 'TOP ARTISTE (1) IMAGE',
        'desc'        => 'ENTER TOP ARTISTE (1) IMAGE',
        'std'         => 'https://i.ibb.co/0Z6Fxxt/images-5.jpg',
        'type'        => 'upload',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_face_1_title',
        'label'       => 'FEATURED FACE 1 TITLE',
        'desc'        => 'FEATURED FACE 1 TITLE',
        'std'         => 'Jdtrendz Face',
        'type'        => 'text',
        'section'     => 'featured_face',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_1_name',
        'label'       => 'TOP ARTISTE (1) NAME',
        'desc'        => 'TOP ARTISTE (1) NAME',
        'std'         => 'PSquare',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_1_url',
        'label'       => 'TOP ARTISTE (1) URL',
        'desc'        => 'ENTER THE URL TO THE TOP ARTISTE e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 
 'top_artiste_2',
        'label'       => 'TOP ARTISTE (2) IMAGE',
        'desc'        => 'ENTER TOP ARTISTE (2) IMAGE',
        'std'         => 'https://i.ibb.co/0Z6Fxxt/images-5.jpg',
        'type'        => 'upload',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_face_2_title',
        'label'       => 'FEATURED FACE 2 TITLE',
        'desc'        => 'FEATURED FACE 2 TITLE',
        'std'         => 'Jdtrendz Face',
        'type'        => 'text',
        'section'     => 'featured_face',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_2_name',
        'label'       => 'TOP ARTISTE (2) NAME',
        'desc'        => 'TOP ARTISTE (2) NAME',
        'std'         => 'PSquare',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_2_url',
        'label'       => 'TOP ARTISTE (2) URL',
        'desc'        => 'ENTER THE URL TO THE TOP ARTISTE e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
     array(
        'id'          => 
 'top_artiste_3',
        'label'       => 'TOP ARTISTE (3) IMAGE',
        'desc'        => 'ENTER TOP ARTISTE (3) IMAGE',
        'std'         => 'https://i.ibb.co/0Z6Fxxt/images-5.jpg',
        'type'        => 'upload',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_face_3_title',
        'label'       => 'FEATURED FACE 3 TITLE',
        'desc'        => 'FEATURED FACE 3 TITLE',
        'std'         => 'Jdtrendz Face',
        'type'        => 'text',
        'section'     => 'featured_face',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_3_name',
        'label'       => 'TOP ARTISTE (3) NAME',
        'desc'        => 'TOP ARTISTE (3) NAME',
        'std'         => 'PSquare',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_3_url',
        'label'       => 'TOP ARTISTE (3) URL',
        'desc'        => 'ENTER THE URL TO THE TOP ARTISTE e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(
        'id'          => 
 'top_artiste_4',
        'label'       => 'TOP ARTISTE (4) IMAGE',
        'desc'        => 'ENTER TOP ARTISTE (4) IMAGE',
        'std'         => 'https://i.ibb.co/0Z6Fxxt/images-5.jpg',
        'type'        => 'upload',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_face_4_title',
        'label'       => 'FEATURED FACE 4 TITLE',
        'desc'        => 'FEATURED FACE 4 TITLE',
        'std'         => 'Jdtrendz Face',
        'type'        => 'text',
        'section'     => 'featured_face',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_4_name',
        'label'       => 'TOP ARTISTE (4) NAME',
        'desc'        => 'TOP ARTISTE (4) NAME',
        'std'         => 'PSquare',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_4_url',
        'label'       => 'TOP ARTISTE (4) URL',
        'desc'        => 'ENTER THE URL TO THE TOP ARTISTE e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(
        'id'          => 
 'top_artiste_5',
        'label'       => 'TOP ARTISTE (5) IMAGE',
        'desc'        => 'ENTER TOP ARTISTE (5) IMAGE',
        'std'         => 'https://i.ibb.co/0Z6Fxxt/images-5.jpg',
        'type'        => 'upload',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_face_5_title',
        'label'       => 'FEATURED FACE 5 TITLE',
        'desc'        => 'FEATURED FACE 5 TITLE',
        'std'         => 'Jdtrendz Face',
        'type'        => 'text',
        'section'     => 'featured_face',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_5_name',
        'label'       => 'TOP ARTISTE (5) NAME',
        'desc'        => 'TOP ARTISTE (5) NAME',
        'std'         => 'PSquare',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_5_url',
        'label'       => 'TOP ARTISTE (5) URL',
        'desc'        => 'ENTER THE URL TO THE TOP ARTISTE e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(
        'id'          => 
 'top_artiste_6',
        'label'       => 'TOP ARTISTE (6) IMAGE',
        'desc'        => 'ENTER TOP ARTISTE (6) IMAGE',
        'std'         => 'https://i.ibb.co/0Z6Fxxt/images-5.jpg',
        'type'        => 'upload',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'featured_face_6_title',
        'label'       => 'FEATURED FACE 6 TITLE',
        'desc'        => 'FEATURED FACE 6 TITLE',
        'std'         => 'Jdtrendz Face',
        'type'        => 'text',
        'section'     => 'featured_face',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_6_name',
        'label'       => 'TOP ARTISTE (6) NAME',
        'desc'        => 'TOP ARTISTE (6) NAME',
        'std'         => 'PSquare',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'top_artiste_6_url',
        'label'       => 'TOP ARTISTE (6) URL',
        'desc'        => 'ENTER THE URL TO THE TOP ARTISTE e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'top_artiste',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
'id'          => 
  'sticky_ads_music_ofday',
        'label'       => 'STICKY ADS MUSIC OF THE DAY HEADER TITLE (A)',
        'desc'        => 'Enter the header title, eg JD Music of the Day',
        'std'         => 'JD Music of the Day',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sticky_musicoftheday_songtitle',
        'label'       => 'SONG TITLE (A)',
        'desc'        => 'Enter the Title of the Song, eg Blow (SoundMan EP)',
        'std'         => 'Blow (SoundMan EP)',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
'id'          => 'sticky_musicoftheday_artiste',
        'label'       => 'SONG ARTISTE (A)',
        'desc'        => 'Enter the Name of the Artiste, eg Wizkid',
        'std'         => 'Wizkid',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sticky_music_url',
        'label'       => 'STICKY MUSIC URL (A)',
        'desc'        => 'ENTER THE URL TO THE MUSIC OF  THE DAY e.g http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'std'         => 'http://demo1.jdtrendz.com/tag/Jdtrendz/',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(
'id'          => 'sticky_music_image1',
        'label'       => 'STICKY MUSIC IMAGE URL (A)',
        'desc'        => 'ENTER THE IMAGE URL TO THE MUSIC OF THE DAY e.g https://www.naijaloaded.com.ng/wp-content/uploads/2019/12/StarBoy-SoundMan-Vol-1-EP.jpg',
        'std'         => 'https://www.naijaloaded.com.ng/wp-content/uploads/2019/12/StarBoy-SoundMan-Vol-1-EP.jpg',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(
'id'          => 'sticky_music_image2',
        'label'       => 'STICKY IMAGE URL (B)',
        'desc'        => 'ENTER AN IMAGE URL (B)..  e.g https://www.naijaloaded.com.ng/wp-content/uploads/2019/11/IMG-20191127-WA0043.jpg',
        'std'         => 'https://www.naijaloaded.com.ng/wp-content/uploads/2019/11/IMG-20191127-WA0043.jpg',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(
'id'          => 'sticky_music_image_url2',
        'label'       => 'STICKY POST URL (B)',
        'desc'        => 'ENTER THE POST URL (B)..  e.g http://demo.jdtrendz.com/tags/jdtrendz',
        'std'         => 'http://demo.jdtrendz.com/tags/jdtrendz',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(
'id'          => 'sticky_music_image3',
        'label'       => 'STICKY IMAGE URL (C)',
        'desc'        => 'ENTER AN IMAGE URL (B)..  e.g https://www.naijaloaded.com.ng/wp-content/uploads/2020/10/bitcoin-site-ads-2-1.png',
        'std'         => 'https://www.naijaloaded.com.ng/wp-content/uploads/2020/10/bitcoin-site-ads-2-1.png',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(
'id'          => 'sticky_music_image_url3',
        'label'       => 'STICKY POST URL (C)',
        'desc'        => 'ENTER THE POST URL (B)..  e.g http://demo.jdtrendz.com/tags/jdtrendz',
        'std'         => 'http://demo.jdtrendz.com/tags/jdtrendz',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(
'id'          => 'sticky_ads_code1',
        'label'       => 'STICKY ADS CODE (1)',
        'desc'        => 'ENTER AN ADS SCRIPT. Make sure your script has the same width e.g ',
        'std'         => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" type="1c012376eb4558dd58f204f1-text/javascript"></script>',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(
'id'          => 'sticky_ads_code2',
        'label'       => 'STICKY ADS CODE (2)',
        'desc'        => 'ENTER AN ADS SCRIPT. Make sure your script has the same width e.g ',
        'std'         => '<script type="1c012376eb4558dd58f204f1-text/javascript">
(adsbygoogle=window.adsbygoogle || []).push({});
</script>',
        'type'        => 'text',
        'section'     => 'sticky_adsfooter',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(        
        'id'          => 'post_watermark_url',
        'label'       => 'POST WATERMARK IMAGE',
        'desc'        => 'Enter Link to Your Watermark Image e.g https://i.ibb.co/jWZLQLt/cropped-1593983065326.png',
        'std'         => 'https://i.ibb.co/jWZLQLt/cropped-1593983065326.png',
        'type'        => 'text',
        'section'     => 'post_watermark',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(        
        'id'          => 'browser_bar_url',
        'label'       => 'Put the Color you Want to Replace the Current One',
        'desc'        => 'Enter code/color name  e.g #21252c or black',
        'std'         => '#21252c',
        'type'        => 'text',
        'section'     => 'browser_bar_bg',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
array(        
        'id'          => 'facebook_username',
        'label'       => 'Facebook Username',
        'desc'        => 'Enter Your Facebook Username e.g jdtrendz',
        'std'         => 'jdtrendz',
        'type'        => 'text',
        'section'     => 'social_media',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'instagram_username',
        'label'       => 'Instagram Username',
        'desc'        => 'Enter Your Instagram Username e.g jdtrendz',
        'std'         => 'jdtrendz',
        'type'        => 'text',
        'section'     => 'social_media',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'phone_number',
        'label'       => 'Phone Number',
        'desc'        => 'Enter Your Phone Number e.g 2349025925116',
        'std'         => '23481098743',
        'type'        => 'text',
        'section'     => 'social_media',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'youtube_channel_url',
        'label'       => 'YouTube Channel url',
        'desc'        => 'Enter your youtube channel url e.g https://www.youtube.com/channel/Pouy6t44fhuu6',
        'std'         => 'https://www.youtube.com/channel/pouy6t44fhuu6',
        'type'        => 'text',
        'section'     => 'social_media',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      )
    )
  );
  
  /* allow settings to be filtered before saving */
  $custom_settings = apply_filters( ot_settings_id() . '_args', $custom_settings );
  
  /* settings are not the same update the DB */
  if ( $saved_settings !== $custom_settings ) {
    update_option( ot_settings_id(), $custom_settings ); 
  }
  
  /* Lets OptionTree know the UI Builder is being overridden */
  global $ot_has_custom_theme_options;
  $ot_has_custom_theme_options = true;
  
}